
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "Job Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      >
      <body className="min-h-full flex flex-col bg-teal-100">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
